-- ----------------------------
-- Table structure for "FT_COLOR_ZODIAC"
-- ----------------------------
-- DROP TABLE "FT_COLOR_ZODIAC";
CREATE TABLE "FT_COLOR_ZODIAC" (
	"GMT_CREATE" VARCHAR2(32 BYTE) NULL ,
	"GMT_MODIFIED" VARCHAR2(32 BYTE) NULL ,
	"SCENE_ID" VARCHAR2(100 BYTE) NULL ,
	"COLOR1" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC1" VARCHAR2(255 BYTE) NULL ,
	"COLOR2" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC2" VARCHAR2(255 BYTE) NULL ,
	"COLOR3" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC3" VARCHAR2(255 BYTE) NULL ,
	"COLOR4" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC4" VARCHAR2(255 BYTE) NULL ,
	"COLOR5" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC5" VARCHAR2(255 BYTE) NULL ,
	"COLOR6" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC6" VARCHAR2(255 BYTE) NULL ,
	"COLOR7" VARCHAR2(255 BYTE) NULL ,
	"ZODIAC7" VARCHAR2(255 BYTE) NULL ,
	"COLOR_ZODIAC_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "FT_COLOR_ZODIAC"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."GMT_MODIFIED" IS '更新时间';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."SCENE_ID" IS '第几场的ID';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR1" IS '颜色1';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC1" IS '生肖1';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR2" IS '颜色2';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC2" IS '生肖2';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR3" IS '颜色3';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC3" IS '生肖3';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR4" IS '颜色4';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC4" IS '生肖4';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR5" IS '颜色5';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC5" IS '生肖5';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR6" IS '颜色6';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC6" IS '生肖6';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR7" IS '颜色7';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."ZODIAC7" IS '生肖7';
COMMENT ON COLUMN "FT_COLOR_ZODIAC"."COLOR_ZODIAC_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table FT_COLOR_ZODIAC
-- ----------------------------

-- ----------------------------
-- Checks structure for table "FT_COLOR_ZODIAC"

-- ----------------------------

ALTER TABLE "FT_COLOR_ZODIAC" ADD CHECK ("COLOR_ZODIAC_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "FT_COLOR_ZODIAC"
-- ----------------------------
ALTER TABLE "FT_COLOR_ZODIAC" ADD PRIMARY KEY ("COLOR_ZODIAC_ID");
