
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `FT_COLOR_ZODIAC`
-- ----------------------------
DROP TABLE IF EXISTS `FT_COLOR_ZODIAC`;
CREATE TABLE `FT_COLOR_ZODIAC` (
 		`COLOR_ZODIAC_ID` varchar(100) NOT NULL,
		`GMT_CREATE` varchar(32) DEFAULT NULL COMMENT '创建时间',
		`GMT_MODIFIED` varchar(32) DEFAULT NULL COMMENT '更新时间',
		`SCENE_ID` varchar(100) DEFAULT NULL COMMENT '第几场的ID',
		`COLOR1` varchar(255) DEFAULT NULL COMMENT '颜色1',
		`ZODIAC1` varchar(255) DEFAULT NULL COMMENT '生肖1',
		`COLOR2` varchar(255) DEFAULT NULL COMMENT '颜色2',
		`ZODIAC2` varchar(255) DEFAULT NULL COMMENT '生肖2',
		`COLOR3` varchar(255) DEFAULT NULL COMMENT '颜色3',
		`ZODIAC3` varchar(255) DEFAULT NULL COMMENT '生肖3',
		`COLOR4` varchar(255) DEFAULT NULL COMMENT '颜色4',
		`ZODIAC4` varchar(255) DEFAULT NULL COMMENT '生肖4',
		`COLOR5` varchar(255) DEFAULT NULL COMMENT '颜色5',
		`ZODIAC5` varchar(255) DEFAULT NULL COMMENT '生肖5',
		`COLOR6` varchar(255) DEFAULT NULL COMMENT '颜色6',
		`ZODIAC6` varchar(255) DEFAULT NULL COMMENT '生肖6',
		`COLOR7` varchar(255) DEFAULT NULL COMMENT '颜色7',
		`ZODIAC7` varchar(255) DEFAULT NULL COMMENT '生肖7',
  		PRIMARY KEY (`COLOR_ZODIAC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
