GO
/******  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE FT_COLOR_ZODIAC (
 		COLOR_ZODIAC_ID  nvarchar(100) NOT NULL,
		GMT_CREATE nvarchar(32) DEFAULT NULL,
		GMT_MODIFIED nvarchar(32) DEFAULT NULL,
		SCENE_ID nvarchar(100) DEFAULT NULL,
		COLOR1 nvarchar(255) DEFAULT NULL,
		ZODIAC1 nvarchar(255) DEFAULT NULL,
		COLOR2 nvarchar(255) DEFAULT NULL,
		ZODIAC2 nvarchar(255) DEFAULT NULL,
		COLOR3 nvarchar(255) DEFAULT NULL,
		ZODIAC3 nvarchar(255) DEFAULT NULL,
		COLOR4 nvarchar(255) DEFAULT NULL,
		ZODIAC4 nvarchar(255) DEFAULT NULL,
		COLOR5 nvarchar(255) DEFAULT NULL,
		ZODIAC5 nvarchar(255) DEFAULT NULL,
		COLOR6 nvarchar(255) DEFAULT NULL,
		ZODIAC6 nvarchar(255) DEFAULT NULL,
		COLOR7 nvarchar(255) DEFAULT NULL,
		ZODIAC7 nvarchar(255) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[COLOR_ZODIAC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
